function get_countries_243() {
  //  const {
  //     name,
  //     iso2,
  //     iso3,
  //     phone_code,
  //     capital,
  //     currency,
  //     currency_name,
  //     currency_symbol,
  //     tld,
  //     region,
  //   } = country;

  const c_243 = {
    AF: ["Afghanistan", "AF", "AFG", "93", "Kabul", "AFN", "Afghan afghani", "؋", ".af", "Asia"],
    AX: ["Aland Islands", "AX", "ALA", "+358-18", "Mariehamn", "EUR", "Euro", "€", ".ax", "Europe"],
    AL: ["Albania", "AL", "ALB", "355", "Tirana", "ALL", "Albanian lek", "Lek", ".al", "Europe"],
    DZ: ["Algeria", "DZ", "DZA", "213", "Algiers", "DZD", "Algerian dinar", "دج", ".dz", "Africa"],
    AS: ["American Samoa", "AS", "ASM", "+1-684", "Pago Pago", "USD", "US Dollar", "$", ".as", "Oceania"],
    AD: ["Andorra", "AD", "AND", "376", "Andorra la Vella", "EUR", "Euro", "€", ".ad", "Europe"],
    AO: ["Angola", "AO", "AGO", "244", "Luanda", "AOA", "Angolan kwanza", "Kz", ".ao", "Africa"],
    AI: ["Anguilla", "AI", "AIA", "+1-264", "The Valley", "XCD", "East Caribbean dollar", "$", ".ai", "Americas"],
    AQ: ["Antarctica", "AQ", "ATA", "672", "", "AAD", "Antarctican dollar", "$", ".aq", "Polar"],
    AG: ["Antigua And Barbuda", "AG", "ATG", "+1-268", "St. John's", "XCD", "Eastern Caribbean dollar", "$", ".ag", "Americas"],
    AR: ["Argentina", "AR", "ARG", "54", "Buenos Aires", "ARS", "Argentine peso", "$", ".ar", "Americas"],
    AM: ["Armenia", "AM", "ARM", "374", "Yerevan", "AMD", "Armenian dram", "֏", ".am", "Asia"],
    AW: ["Aruba", "AW", "ABW", "297", "Oranjestad", "AWG", "Aruban florin", "ƒ", ".aw", "Americas"],
    AU: ["Australia", "AU", "AUS", "61", "Canberra", "AUD", "Australian dollar", "$", ".au", "Oceania"],
    AT: ["Austria", "AT", "AUT", "43", "Vienna", "EUR", "Euro", "€", ".at", "Europe"],
    AZ: ["Azerbaijan", "AZ", "AZE", "994", "Baku", "AZN", "Azerbaijani manat", "m", ".az", "Asia"],
    BH: ["Bahrain", "BH", "BHR", "973", "Manama", "BHD", "Bahraini dinar", ".د.ب", ".bh", "Asia"],
    BD: ["Bangladesh", "BD", "BGD", "880", "Dhaka", "BDT", "Bangladeshi taka", "৳", ".bd", "Asia"],
    BB: ["Barbados", "BB", "BRB", "+1-246", "Bridgetown", "BBD", "Barbadian dollar", "Bds$", ".bb", "Americas"],
    BY: ["Belarus", "BY", "BLR", "375", "Minsk", "BYN", "Belarusian ruble", "Br", ".by", "Europe"],
    BE: ["Belgium", "BE", "BEL", "32", "Brussels", "EUR", "Euro", "€", ".be", "Europe"],
    BZ: ["Belize", "BZ", "BLZ", "501", "Belmopan", "BZD", "Belize dollar", "$", ".bz", "Americas"],
    BJ: ["Benin", "BJ", "BEN", "229", "Porto-Novo", "XOF", "West African CFA franc", "CFA", ".bj", "Africa"],
    BM: ["Bermuda", "BM", "BMU", "+1-441", "Hamilton", "BMD", "Bermudian dollar", "$", ".bm", "Americas"],
    BT: ["Bhutan", "BT", "BTN", "975", "Thimphu", "BTN", "Bhutanese ngultrum", "Nu.", ".bt", "Asia"],
    BO: ["Bolivia", "BO", "BOL", "591", "Sucre", "BOB", "Bolivian boliviano", "Bs.", ".bo", "Americas"],
    BQ: ["Bonaire, Sint Eustatius and Saba", "BQ", "BES", "599", "Kralendijk", "USD", "United States dollar", "$", ".an", "Americas"],
    BA: ["Bosnia and Herzegovina", "BA", "BIH", "387", "Sarajevo", "BAM", "Bosnia and Herzegovina convertible mark", "KM", ".ba", "Europe"],
    BW: ["Botswana", "BW", "BWA", "267", "Gaborone", "BWP", "Botswana pula", "P", ".bw", "Africa"],
    BV: ["Bouvet Island", "BV", "BVT", "0055", "", "NOK", "Norwegian Krone", "kr", ".bv", ""],
    BR: ["Brazil", "BR", "BRA", "55", "Brasilia", "BRL", "Brazilian real", "R$", ".br", "Americas"],
    IO: ["British Indian Ocean Territory", "IO", "IOT", "246", "Diego Garcia", "USD", "United States dollar", "$", ".io", "Africa"],
    BN: ["Brunei", "BN", "BRN", "673", "Bandar Seri Begawan", "BND", "Brunei dollar", "B$", ".bn", "Asia"],
    BG: ["Bulgaria", "BG", "BGR", "359", "Sofia", "BGN", "Bulgarian lev", "Лв.", ".bg", "Europe"],
    BF: ["Burkina Faso", "BF", "BFA", "226", "Ouagadougou", "XOF", "West African CFA franc", "CFA", ".bf", "Africa"],
    BI: ["Burundi", "BI", "BDI", "257", "Bujumbura", "BIF", "Burundian franc", "FBu", ".bi", "Africa"],
    KH: ["Cambodia", "KH", "KHM", "855", "Phnom Penh", "KHR", "Cambodian riel", "KHR", ".kh", "Asia"],
    CM: ["Cameroon", "CM", "CMR", "237", "Yaounde", "XAF", "Central African CFA franc", "FCFA", ".cm", "Africa"],
    CA: ["Canada", "CA", "CAN", "1", "Ottawa", "CAD", "Canadian dollar", "$", ".ca", "Americas"],
    CV: ["Cape Verde", "CV", "CPV", "238", "Praia", "CVE", "Cape Verdean escudo", "$", ".cv", "Africa"],
    KY: ["Cayman Islands", "KY", "CYM", "+1-345", "George Town", "KYD", "Cayman Islands dollar", "$", ".ky", "Americas"],
    CF: ["Central African Republic", "CF", "CAF", "236", "Bangui", "XAF", "Central African CFA franc", "FCFA", ".cf", "Africa"],
    TD: ["Chad", "TD", "TCD", "235", "N'Djamena", "XAF", "Central African CFA franc", "FCFA", ".td", "Africa"],
    CL: ["Chile", "CL", "CHL", "56", "Santiago", "CLP", "Chilean peso", "$", ".cl", "Americas"],
    CN: ["China", "CN", "CHN", "86", "Beijing", "CNY", "Chinese yuan", "¥", ".cn", "Asia"],
    CX: ["Christmas Island", "CX", "CXR", "61", "Flying Fish Cove", "AUD", "Australian dollar", "$", ".cx", "Oceania"],
    CC: ["Cocos (Keeling) Islands", "CC", "CCK", "61", "West Island", "AUD", "Australian dollar", "$", ".cc", "Oceania"],
    CO: ["Colombia", "CO", "COL", "57", "Bogotá", "COP", "Colombian peso", "$", ".co", "Americas"],
    KM: ["Comoros", "KM", "COM", "269", "Moroni", "KMF", "Comorian franc", "CF", ".km", "Africa"],
    CG: ["Congo", "CG", "COG", "242", "Brazzaville", "XAF", "Central African CFA franc", "FC", ".cg", "Africa"],
    CK: ["Cook Islands", "CK", "COK", "682", "Avarua", "NZD", "Cook Islands dollar", "$", ".ck", "Oceania"],
    CR: ["Costa Rica", "CR", "CRI", "506", "San Jose", "CRC", "Costa Rican colón", "₡", ".cr", "Americas"],
    CI: ["Cote D'Ivoire (Ivory Coast)", "CI", "CIV", "225", "Yamoussoukro", "XOF", "West African CFA franc", "CFA", ".ci", "Africa"],
    HR: ["Croatia", "HR", "HRV", "385", "Zagreb", "HRK", "Croatian kuna", "kn", ".hr", "Europe"],
    CU: ["Cuba", "CU", "CUB", "53", "Havana", "CUP", "Cuban peso", "$", ".cu", "Americas"],
    CW: ["Curaçao", "CW", "CUW", "599", "Willemstad", "ANG", "Netherlands Antillean guilder", "ƒ", ".cw", "Americas"],
    CY: ["Cyprus", "CY", "CYP", "357", "Nicosia", "EUR", "Euro", "€", ".cy", "Europe"],
    CZ: ["Czech Republic", "CZ", "CZE", "420", "Prague", "CZK", "Czech koruna", "Kč", ".cz", "Europe"],
    CD: ["Democratic Republic of the Congo", "CD", "COD", "243", "Kinshasa", "CDF", "Congolese Franc", "FC", ".cd", "Africa"],
    DK: ["Denmark", "DK", "DNK", "45", "Copenhagen", "DKK", "Danish krone", "Kr.", ".dk", "Europe"],
    DJ: ["Djibouti", "DJ", "DJI", "253", "Djibouti", "DJF", "Djiboutian franc", "Fdj", ".dj", "Africa"],
    DM: ["Dominica", "DM", "DMA", "+1-767", "Roseau", "XCD", "Eastern Caribbean dollar", "$", ".dm", "Americas"],
    DO: ["Dominican Republic", "DO", "DOM", "+1-809 and 1-829", "Santo Domingo", "DOP", "Dominican peso", "$", ".do", "Americas"],
    TL: ["East Timor", "TL", "TLS", "670", "Dili", "USD", "United States dollar", "$", ".tl", "Asia"],
    EC: ["Ecuador", "EC", "ECU", "593", "Quito", "USD", "United States dollar", "$", ".ec", "Americas"],
    EG: ["Egypt", "EG", "EGY", "20", "Cairo", "EGP", "Egyptian pound", "ج.م", ".eg", "Africa"],
    SV: ["El Salvador", "SV", "SLV", "503", "San Salvador", "USD", "United States dollar", "$", ".sv", "Americas"],
    GQ: ["Equatorial Guinea", "GQ", "GNQ", "240", "Malabo", "XAF", "Central African CFA franc", "FCFA", ".gq", "Africa"],
    ER: ["Eritrea", "ER", "ERI", "291", "Asmara", "ERN", "Eritrean nakfa", "Nfk", ".er", "Africa"],
    EE: ["Estonia", "EE", "EST", "372", "Tallinn", "EUR", "Euro", "€", ".ee", "Europe"],
    ET: ["Ethiopia", "ET", "ETH", "251", "Addis Ababa", "ETB", "Ethiopian birr", "Nkf", ".et", "Africa"],
    FK: ["Falkland Islands", "FK", "FLK", "500", "Stanley", "FKP", "Falkland Islands pound", "£", ".fk", "Americas"],
    FO: ["Faroe Islands", "FO", "FRO", "298", "Torshavn", "DKK", "Danish krone", "Kr.", ".fo", "Europe"],
    FJ: ["Fiji Islands", "FJ", "FJI", "679", "Suva", "FJD", "Fijian dollar", "FJ$", ".fj", "Oceania"],
    FI: ["Finland", "FI", "FIN", "358", "Helsinki", "EUR", "Euro", "€", ".fi", "Europe"],
    FR: ["France", "FR", "FRA", "33", "Paris", "EUR", "Euro", "€", ".fr", "Europe"],
    GF: ["French Guiana", "GF", "GUF", "594", "Cayenne", "EUR", "Euro", "€", ".gf", "Americas"],
    PF: ["French Polynesia", "PF", "PYF", "689", "Papeete", "XPF", "CFP franc", "₣", ".pf", "Oceania"],
    TF: ["French Southern Territories", "TF", "ATF", "262", "Port-aux-Francais", "EUR", "Euro", "€", ".tf", "Africa"],
    GA: ["Gabon", "GA", "GAB", "241", "Libreville", "XAF", "Central African CFA franc", "FCFA", ".ga", "Africa"],
    GM: ["Gambia The", "GM", "GMB", "220", "Banjul", "GMD", "Gambian dalasi", "D", ".gm", "Africa"],
    GE: ["Georgia", "GE", "GEO", "995", "Tbilisi", "GEL", "Georgian lari", "ლ", ".ge", "Asia"],
    DE: ["Germany", "DE", "DEU", "49", "Berlin", "EUR", "Euro", "€", ".de", "Europe"],
    GH: ["Ghana", "GH", "GHA", "233", "Accra", "GHS", "Ghanaian cedi", "GH₵", ".gh", "Africa"],
    GI: ["Gibraltar", "GI", "GIB", "350", "Gibraltar", "GIP", "Gibraltar pound", "£", ".gi", "Europe"],
    GR: ["Greece", "GR", "GRC", "30", "Athens", "EUR", "Euro", "€", ".gr", "Europe"],
    GL: ["Greenland", "GL", "GRL", "299", "Nuuk", "DKK", "Danish krone", "Kr.", ".gl", "Americas"],
    GD: ["Grenada", "GD", "GRD", "+1-473", "St. George's", "XCD", "Eastern Caribbean dollar", "$", ".gd", "Americas"],
    GP: ["Guadeloupe", "GP", "GLP", "590", "Basse-Terre", "EUR", "Euro", "€", ".gp", "Americas"],
    GU: ["Guam", "GU", "GUM", "+1-671", "Hagatna", "USD", "US Dollar", "$", ".gu", "Oceania"],
    GT: ["Guatemala", "GT", "GTM", "502", "Guatemala City", "GTQ", "Guatemalan quetzal", "Q", ".gt", "Americas"],
    GG: ["Guernsey and Alderney", "GG", "GGY", "+44-1481", "St Peter Port", "GBP", "British pound", "£", ".gg", "Europe"],
    GN: ["Guinea", "GN", "GIN", "224", "Conakry", "GNF", "Guinean franc", "FG", ".gn", "Africa"],
    GW: ["Guinea-Bissau", "GW", "GNB", "245", "Bissau", "XOF", "West African CFA franc", "CFA", ".gw", "Africa"],
    GY: ["Guyana", "GY", "GUY", "592", "Georgetown", "GYD", "Guyanese dollar", "$", ".gy", "Americas"],
    HT: ["Haiti", "HT", "HTI", "509", "Port-au-Prince", "HTG", "Haitian gourde", "G", ".ht", "Americas"],
    HM: ["Heard Island and McDonald Islands", "HM", "HMD", "672", "", "AUD", "Australian dollar", "$", ".hm", ""],
    HN: ["Honduras", "HN", "HND", "504", "Tegucigalpa", "HNL", "Honduran lempira", "L", ".hn", "Americas"],
    HK: ["Hong Kong S.A.R.", "HK", "HKG", "852", "Hong Kong", "HKD", "Hong Kong dollar", "$", ".hk", "Asia"],
    HU: ["Hungary", "HU", "HUN", "36", "Budapest", "HUF", "Hungarian forint", "Ft", ".hu", "Europe"],
    IS: ["Iceland", "IS", "ISL", "354", "Reykjavik", "ISK", "Icelandic króna", "kr", ".is", "Europe"],
    IN: ["India", "IN", "IND", "91", "New Delhi", "INR", "Indian rupee", "₹", ".in", "Asia"],
    ID: ["Indonesia", "ID", "IDN", "62", "Jakarta", "IDR", "Indonesian rupiah", "Rp", ".id", "Asia"],
    IR: ["Iran", "IR", "IRN", "98", "Tehran", "IRR", "Iranian rial", "﷼", ".ir", "Asia"],
    IQ: ["Iraq", "IQ", "IRQ", "964", "Baghdad", "IQD", "Iraqi dinar", "د.ع", ".iq", "Asia"],
    IE: ["Ireland", "IE", "IRL", "353", "Dublin", "EUR", "Euro", "€", ".ie", "Europe"],
    IL: ["Israel", "IL", "ISR", "972", "Jerusalem", "ILS", "Israeli new shekel", "₪", ".il", "Asia"],
    IT: ["Italy", "IT", "ITA", "39", "Rome", "EUR", "Euro", "€", ".it", "Europe"],
    JM: ["Jamaica", "JM", "JAM", "+1-876", "Kingston", "JMD", "Jamaican dollar", "J$", ".jm", "Americas"],
    JP: ["Japan", "JP", "JPN", "81", "Tokyo", "JPY", "Japanese yen", "¥", ".jp", "Asia"],
    JE: ["Jersey", "JE", "JEY", "+44-1534", "Saint Helier", "GBP", "British pound", "£", ".je", "Europe"],
    JO: ["Jordan", "JO", "JOR", "962", "Amman", "JOD", "Jordanian dinar", "ا.د", ".jo", "Asia"],
    KZ: ["Kazakhstan", "KZ", "KAZ", "7", "Astana", "KZT", "Kazakhstani tenge", "лв", ".kz", "Asia"],
    KE: ["Kenya", "KE", "KEN", "254", "Nairobi", "KES", "Kenyan shilling", "KSh", ".ke", "Africa"],
    KI: ["Kiribati", "KI", "KIR", "686", "Tarawa", "AUD", "Australian dollar", "$", ".ki", "Oceania"],
    XK: ["Kosovo", "XK", "XKX", "383", "Pristina", "EUR", "Euro", "€", ".xk", "Europe"],
    KW: ["Kuwait", "KW", "KWT", "965", "Kuwait City", "KWD", "Kuwaiti dinar", "ك.د", ".kw", "Asia"],
    KG: ["Kyrgyzstan", "KG", "KGZ", "996", "Bishkek", "KGS", "Kyrgyzstani som", "лв", ".kg", "Asia"],
    LA: ["Laos", "LA", "LAO", "856", "Vientiane", "LAK", "Lao kip", "₭", ".la", "Asia"],
    LV: ["Latvia", "LV", "LVA", "371", "Riga", "EUR", "Euro", "€", ".lv", "Europe"],
    LB: ["Lebanon", "LB", "LBN", "961", "Beirut", "LBP", "Lebanese pound", "£", ".lb", "Asia"],
    LS: ["Lesotho", "LS", "LSO", "266", "Maseru", "LSL", "Lesotho loti", "L", ".ls", "Africa"],
    LR: ["Liberia", "LR", "LBR", "231", "Monrovia", "LRD", "Liberian dollar", "$", ".lr", "Africa"],
    LY: ["Libya", "LY", "LBY", "218", "Tripolis", "LYD", "Libyan dinar", "د.ل", ".ly", "Africa"],
    LI: ["Liechtenstein", "LI", "LIE", "423", "Vaduz", "CHF", "Swiss franc", "CHf", ".li", "Europe"],
    LT: ["Lithuania", "LT", "LTU", "370", "Vilnius", "EUR", "Euro", "€", ".lt", "Europe"],
    LU: ["Luxembourg", "LU", "LUX", "352", "Luxembourg", "EUR", "Euro", "€", ".lu", "Europe"],
    MO: ["Macau S.A.R.", "MO", "MAC", "853", "Macao", "MOP", "Macanese pataca", "$", ".mo", "Asia"],
    MK: ["Macedonia", "MK", "MKD", "389", "Skopje", "MKD", "Denar", "ден", ".mk", "Europe"],
    MG: ["Madagascar", "MG", "MDG", "261", "Antananarivo", "MGA", "Malagasy ariary", "Ar", ".mg", "Africa"],
    MW: ["Malawi", "MW", "MWI", "265", "Lilongwe", "MWK", "Malawian kwacha", "MK", ".mw", "Africa"],
    MY: ["Malaysia", "MY", "MYS", "60", "Kuala Lumpur", "MYR", "Malaysian ringgit", "RM", ".my", "Asia"],
    MV: ["Maldives", "MV", "MDV", "960", "Male", "MVR", "Maldivian rufiyaa", "Rf", ".mv", "Asia"],
    ML: ["Mali", "ML", "MLI", "223", "Bamako", "XOF", "West African CFA franc", "CFA", ".ml", "Africa"],
    MT: ["Malta", "MT", "MLT", "356", "Valletta", "EUR", "Euro", "€", ".mt", "Europe"],
    IM: ["Man (Isle of)", "IM", "IMN", "+44-1624", "Douglas, Isle of Man", "GBP", "British pound", "£", ".im", "Europe"],
    MH: ["Marshall Islands", "MH", "MHL", "692", "Majuro", "USD", "United States dollar", "$", ".mh", "Oceania"],
    MQ: ["Martinique", "MQ", "MTQ", "596", "Fort-de-France", "EUR", "Euro", "€", ".mq", "Americas"],
    MR: ["Mauritania", "MR", "MRT", "222", "Nouakchott", "MRO", "Mauritanian ouguiya", "MRU", ".mr", "Africa"],
    MU: ["Mauritius", "MU", "MUS", "230", "Port Louis", "MUR", "Mauritian rupee", "₨", ".mu", "Africa"],
    YT: ["Mayotte", "YT", "MYT", "262", "Mamoudzou", "EUR", "Euro", "€", ".yt", "Africa"],
    MX: ["Mexico", "MX", "MEX", "52", "Ciudad de México", "MXN", "Mexican peso", "$", ".mx", "Americas"],
    FM: ["Micronesia", "FM", "FSM", "691", "Palikir", "USD", "United States dollar", "$", ".fm", "Oceania"],
    MD: ["Moldova", "MD", "MDA", "373", "Chisinau", "MDL", "Moldovan leu", "L", ".md", "Europe"],
    MC: ["Monaco", "MC", "MCO", "377", "Monaco", "EUR", "Euro", "€", ".mc", "Europe"],
    MN: ["Mongolia", "MN", "MNG", "976", "Ulan Bator", "MNT", "Mongolian tögrög", "₮", ".mn", "Asia"],
    ME: ["Montenegro", "ME", "MNE", "382", "Podgorica", "EUR", "Euro", "€", ".me", "Europe"],
    MS: ["Montserrat", "MS", "MSR", "+1-664", "Plymouth", "XCD", "Eastern Caribbean dollar", "$", ".ms", "Americas"],
    MA: ["Morocco", "MA", "MAR", "212", "Rabat", "MAD", "Moroccan dirham", "DH", ".ma", "Africa"],
    MZ: ["Mozambique", "MZ", "MOZ", "258", "Maputo", "MZN", "Mozambican metical", "MT", ".mz", "Africa"],
    MM: ["Myanmar", "MM", "MMR", "95", "Nay Pyi Taw", "MMK", "Burmese kyat", "K", ".mm", "Asia"],
    NA: ["Namibia", "NA", "NAM", "264", "Windhoek", "NAD", "Namibian dollar", "$", ".na", "Africa"],
    NR: ["Nauru", "NR", "NRU", "674", "Yaren", "AUD", "Australian dollar", "$", ".nr", "Oceania"],
    NP: ["Nepal", "NP", "NPL", "977", "Kathmandu", "NPR", "Nepalese rupee", "₨", ".np", "Asia"],
    NL: ["Netherlands", "NL", "NLD", "31", "Amsterdam", "EUR", "Euro", "€", ".nl", "Europe"],
    NC: ["New Caledonia", "NC", "NCL", "687", "Noumea", "XPF", "CFP franc", "₣", ".nc", "Oceania"],
    NZ: ["New Zealand", "NZ", "NZL", "64", "Wellington", "NZD", "New Zealand dollar", "$", ".nz", "Oceania"],
    NI: ["Nicaragua", "NI", "NIC", "505", "Managua", "NIO", "Nicaraguan córdoba", "C$", ".ni", "Americas"],
    NE: ["Niger", "NE", "NER", "227", "Niamey", "XOF", "West African CFA franc", "CFA", ".ne", "Africa"],
    NG: ["Nigeria", "NG", "NGA", "234", "Abuja", "NGN", "Nigerian naira", "₦", ".ng", "Africa"],
    NU: ["Niue", "NU", "NIU", "683", "Alofi", "NZD", "New Zealand dollar", "$", ".nu", "Oceania"],
    NF: ["Norfolk Island", "NF", "NFK", "672", "Kingston", "AUD", "Australian dollar", "$", ".nf", "Oceania"],
    KP: ["North Korea", "KP", "PRK", "850", "Pyongyang", "KPW", "North Korean Won", "₩", ".kp", "Asia"],
    MP: ["Northern Mariana Islands", "MP", "MNP", "+1-670", "Saipan", "USD", "United States dollar", "$", ".mp", "Oceania"],
    NO: ["Norway", "NO", "NOR", "47", "Oslo", "NOK", "Norwegian krone", "kr", ".no", "Europe"],
    OM: ["Oman", "OM", "OMN", "968", "Muscat", "OMR", "Omani rial", ".ع.ر", ".om", "Asia"],
    PK: ["Pakistan", "PK", "PAK", "92", "Islamabad", "PKR", "Pakistani rupee", "₨", ".pk", "Asia"],
    PW: ["Palau", "PW", "PLW", "680", "Melekeok", "USD", "United States dollar", "$", ".pw", "Oceania"],
    PS: ["Palestinian Territory Occupied", "PS", "PSE", "970", "East Jerusalem", "ILS", "Israeli new shekel", "₪", ".ps", "Asia"],
    PA: ["Panama", "PA", "PAN", "507", "Panama City", "PAB", "Panamanian balboa", "B/.", ".pa", "Americas"],
    PG: ["Papua new Guinea", "PG", "PNG", "675", "Port Moresby", "PGK", "Papua New Guinean kina", "K", ".pg", "Oceania"],
    PY: ["Paraguay", "PY", "PRY", "595", "Asuncion", "PYG", "Paraguayan guarani", "₲", ".py", "Americas"],
    PE: ["Peru", "PE", "PER", "51", "Lima", "PEN", "Peruvian sol", "S/.", ".pe", "Americas"],
    PH: ["Philippines", "PH", "PHL", "63", "Manila", "PHP", "Philippine peso", "₱", ".ph", "Asia"],
    PN: ["Pitcairn Island", "PN", "PCN", "870", "Adamstown", "NZD", "New Zealand dollar", "$", ".pn", "Oceania"],
    PL: ["Poland", "PL", "POL", "48", "Warsaw", "PLN", "Polish złoty", "zł", ".pl", "Europe"],
    PT: ["Portugal", "PT", "PRT", "351", "Lisbon", "EUR", "Euro", "€", ".pt", "Europe"],
    PR: ["Puerto Rico", "PR", "PRI", "+1-787 and 1-939", "San Juan", "USD", "United States dollar", "$", ".pr", "Americas"],
    QA: ["Qatar", "QA", "QAT", "974", "Doha", "QAR", "Qatari riyal", "ق.ر", ".qa", "Asia"],
    RE: ["Reunion", "RE", "REU", "262", "Saint-Denis", "EUR", "Euro", "€", ".re", "Africa"],
    RO: ["Romania", "RO", "ROU", "40", "Bucharest", "RON", "Romanian leu", "lei", ".ro", "Europe"],
    RU: ["Russia", "RU", "RUS", "7", "Moscow", "RUB", "Russian ruble", "₽", ".ru", "Europe"],
    RW: ["Rwanda", "RW", "RWA", "250", "Kigali", "RWF", "Rwandan franc", "FRw", ".rw", "Africa"],
    SH: ["Saint Helena", "SH", "SHN", "290", "Jamestown", "SHP", "Saint Helena pound", "£", ".sh", "Africa"],
    KN: ["Saint Kitts And Nevis", "KN", "KNA", "+1-869", "Basseterre", "XCD", "Eastern Caribbean dollar", "$", ".kn", "Americas"],
    LC: ["Saint Lucia", "LC", "LCA", "+1-758", "Castries", "XCD", "Eastern Caribbean dollar", "$", ".lc", "Americas"],
    PM: ["Saint Pierre and Miquelon", "PM", "SPM", "508", "Saint-Pierre", "EUR", "Euro", "€", ".pm", "Americas"],
    VC: ["Saint Vincent And The Grenadines", "VC", "VCT", "+1-784", "Kingstown", "XCD", "Eastern Caribbean dollar", "$", ".vc", "Americas"],
    BL: ["Saint-Barthelemy", "BL", "BLM", "590", "Gustavia", "EUR", "Euro", "€", ".bl", "Americas"],
    MF: ["Saint-Martin (French part)", "MF", "MAF", "590", "Marigot", "EUR", "Euro", "€", ".mf", "Americas"],
    WS: ["Samoa", "WS", "WSM", "685", "Apia", "WST", "Samoan tālā", "SAT", ".ws", "Oceania"],
    SM: ["San Marino", "SM", "SMR", "378", "San Marino", "EUR", "Euro", "€", ".sm", "Europe"],
    ST: ["Sao Tome and Principe", "ST", "STP", "239", "Sao Tome", "STD", "Dobra", "Db", ".st", "Africa"],
    SA: ["Saudi Arabia", "SA", "SAU", "966", "Riyadh", "SAR", "Saudi riyal", "﷼", ".sa", "Asia"],
    SN: ["Senegal", "SN", "SEN", "221", "Dakar", "XOF", "West African CFA franc", "CFA", ".sn", "Africa"],
    RS: ["Serbia", "RS", "SRB", "381", "Belgrade", "RSD", "Serbian dinar", "din", ".rs", "Europe"],
    SC: ["Seychelles", "SC", "SYC", "248", "Victoria", "SCR", "Seychellois rupee", "SRe", ".sc", "Africa"],
    SL: ["Sierra Leone", "SL", "SLE", "232", "Freetown", "SLL", "Sierra Leonean leone", "Le", ".sl", "Africa"],
    SG: ["Singapore", "SG", "SGP", "65", "Singapur", "SGD", "Singapore dollar", "$", ".sg", "Asia"],
    SX: ["Sint Maarten (Dutch part)", "SX", "SXM", "1721", "Philipsburg", "ANG", "Netherlands Antillean guilder", "ƒ", ".sx", "Americas"],
    SK: ["Slovakia", "SK", "SVK", "421", "Bratislava", "EUR", "Euro", "€", ".sk", "Europe"],
    SI: ["Slovenia", "SI", "SVN", "386", "Ljubljana", "EUR", "Euro", "€", ".si", "Europe"],
    SB: ["Solomon Islands", "SB", "SLB", "677", "Honiara", "SBD", "Solomon Islands dollar", "Si$", ".sb", "Oceania"],
    SO: ["Somalia", "SO", "SOM", "252", "Mogadishu", "SOS", "Somali shilling", "Sh.so.", ".so", "Africa"],
    ZA: ["South Africa", "ZA", "ZAF", "27", "Pretoria", "ZAR", "South African rand", "R", ".za", "Africa"],
    GS: ["South Georgia", "GS", "SGS", "500", "Grytviken", "GBP", "British pound", "£", ".gs", "Americas"],
    KR: ["South Korea", "KR", "KOR", "82", "Seoul", "KRW", "Won", "₩", ".kr", "Asia"],
    SS: ["South Sudan", "SS", "SSD", "211", "Juba", "SSP", "South Sudanese pound", "£", ".ss", "Africa"],
    ES: ["Spain", "ES", "ESP", "34", "Madrid", "EUR", "Euro", "€", ".es", "Europe"],
    LK: ["Sri Lanka", "LK", "LKA", "94", "Colombo", "LKR", "Sri Lankan rupee", "Rs", ".lk", "Asia"],
    SD: ["Sudan", "SD", "SDN", "249", "Khartoum", "SDG", "Sudanese pound", ".س.ج", ".sd", "Africa"],
    SR: ["Suriname", "SR", "SUR", "597", "Paramaribo", "SRD", "Surinamese dollar", "$", ".sr", "Americas"],
    SJ: ["Svalbard And Jan Mayen Islands", "SJ", "SJM", "47", "Longyearbyen", "NOK", "Norwegian Krone", "kr", ".sj", "Europe"],
    SZ: ["Swaziland", "SZ", "SWZ", "268", "Mbabane", "SZL", "Lilangeni", "E", ".sz", "Africa"],
    SE: ["Sweden", "SE", "SWE", "46", "Stockholm", "SEK", "Swedish krona", "kr", ".se", "Europe"],
    CH: ["Switzerland", "CH", "CHE", "41", "Bern", "CHF", "Swiss franc", "CHf", ".ch", "Europe"],
    SY: ["Syria", "SY", "SYR", "963", "Damascus", "SYP", "Syrian pound", "LS", ".sy", "Asia"],
    TW: ["Taiwan", "TW", "TWN", "886", "Taipei", "TWD", "New Taiwan dollar", "$", ".tw", "Asia"],
    TJ: ["Tajikistan", "TJ", "TJK", "992", "Dushanbe", "TJS", "Tajikistani somoni", "SM", ".tj", "Asia"],
    TZ: ["Tanzania", "TZ", "TZA", "255", "Dodoma", "TZS", "Tanzanian shilling", "TSh", ".tz", "Africa"],
    TH: ["Thailand", "TH", "THA", "66", "Bangkok", "THB", "Thai baht", "฿", ".th", "Asia"],
    BS: ["The Bahamas", "BS", "BHS", "+1-242", "Nassau", "BSD", "Bahamian dollar", "B$", ".bs", "Americas"],
    TG: ["Togo", "TG", "TGO", "228", "Lome", "XOF", "West African CFA franc", "CFA", ".tg", "Africa"],
    TK: ["Tokelau", "TK", "TKL", "690", "", "NZD", "New Zealand dollar", "$", ".tk", "Oceania"],
    TO: ["Tonga", "TO", "TON", "676", "Nuku'alofa", "TOP", "Tongan paʻanga", "$", ".to", "Oceania"],
    TT: ["Trinidad And Tobago", "TT", "TTO", "+1-868", "Port of Spain", "TTD", "Trinidad and Tobago dollar", "$", ".tt", "Americas"],
    TN: ["Tunisia", "TN", "TUN", "216", "Tunis", "TND", "Tunisian dinar", "ت.د", ".tn", "Africa"],
    TR: ["Turkey", "TR", "TUR", "90", "Ankara", "TRY", "Turkish lira", "₺", ".tr", "Asia"],
    TM: ["Turkmenistan", "TM", "TKM", "993", "Ashgabat", "TMT", "Turkmenistan manat", "T", ".tm", "Asia"],
    TC: ["Turks And Caicos Islands", "TC", "TCA", "+1-649", "Cockburn Town", "USD", "United States dollar", "$", ".tc", "Americas"],
    TV: ["Tuvalu", "TV", "TUV", "688", "Funafuti", "AUD", "Australian dollar", "$", ".tv", "Oceania"],
    UG: ["Uganda", "UG", "UGA", "256", "Kampala", "UGX", "Ugandan shilling", "USh", ".ug", "Africa"],
    UA: ["Ukraine", "UA", "UKR", "380", "Kiev", "UAH", "Ukrainian hryvnia", "₴", ".ua", "Europe"],
    AE: ["United Arab Emirates", "AE", "ARE", "971", "Abu Dhabi", "AED", "United Arab Emirates dirham", "إ.د", ".ae", "Asia"],
    GB: ["United Kingdom", "GB", "GBR", "44", "London", "GBP", "British pound", "£", ".uk", "Europe"],
    US: ["United States", "US", "USA", "1", "Washington", "USD", "United States dollar", "$", ".us", "Americas"],
    UM: ["United States Minor Outlying Islands", "UM", "UMI", "1", "", "USD", "United States dollar", "$", ".us", "Americas"],
    UY: ["Uruguay", "UY", "URY", "598", "Montevideo", "UYU", "Uruguayan peso", "$", ".uy", "Americas"],
    UZ: ["Uzbekistan", "UZ", "UZB", "998", "Tashkent", "UZS", "Uzbekistani soʻm", "лв", ".uz", "Asia"],
    VU: ["Vanuatu", "VU", "VUT", "678", "Port Vila", "VUV", "Vanuatu vatu", "VT", ".vu", "Oceania"],
    VA: ["Vatican City State (Holy See)", "VA", "VAT", "379", "Vatican City", "EUR", "Euro", "€", ".va", "Europe"],
    VE: ["Venezuela", "VE", "VEN", "58", "Caracas", "VEF", "Bolívar", "Bs", ".ve", "Americas"],
    VN: ["Vietnam", "VN", "VNM", "84", "Hanoi", "VND", "Vietnamese đồng", "₫", ".vn", "Asia"],
    VG: ["Virgin Islands (British)", "VG", "VGB", "+1-284", "Road Town", "USD", "United States dollar", "$", ".vg", "Americas"],
    VI: ["Virgin Islands (US)", "VI", "VIR", "+1-340", "Charlotte Amalie", "USD", "United States dollar", "$", ".vi", "Americas"],
    WF: ["Wallis And Futuna Islands", "WF", "WLF", "681", "Mata Utu", "XPF", "CFP franc", "₣", ".wf", "Oceania"],
    EH: ["Western Sahara", "EH", "ESH", "212", "El-Aaiun", "MAD", "Moroccan Dirham", "MAD", ".eh", "Africa"],
    YE: ["Yemen", "YE", "YEM", "967", "Sanaa", "YER", "Yemeni rial", "﷼", ".ye", "Asia"],
    ZM: ["Zambia", "ZM", "ZMB", "260", "Lusaka", "ZMW", "Zambian kwacha", "ZK", ".zm", "Africa"],
    ZW: ["Zimbabwe", "ZW", "ZWE", "263", "Harare", "ZWL", "Zimbabwe Dollar", "$", ".zw", "Africa"]
  };
  return c_243;
}
function createCountriesDataByTimeZones() {
  const c = get_countries_243();
  const countriesCodeByTimeZones = {
    "asia/kabul": c["AF"],
    "europe/mariehamn": c["AX"],
    "europe/tirane": c["AL"],
    "africa/algiers": c["DZ"],
    "pacific/pago_pago": c["AS"],
    "europe/andorra": c["AD"],
    "africa/luanda": c["AO"],
    "america/anguilla": c["SX"],
    "antarctica/casey": c["AQ"],
    "antarctica/davis": c["AQ"],
    "antarctica/dumontdurville": c["AQ"],
    "antarctica/mawson": c["AQ"],
    "antarctica/mcmurdo": c["AQ"],
    "antarctica/palmer": c["AQ"],
    "antarctica/rothera": c["AQ"],
    "antarctica/syowa": c["AQ"],
    "antarctica/troll": c["AQ"],
    "antarctica/vostok": c["AQ"],
    "america/antigua": c["AG"],
    "america/argentina/buenos_aires": c["AR"],
    "america/argentina/catamarca": c["AR"],
    "america/argentina/cordoba": c["AR"],
    "america/argentina/jujuy": c["AR"],
    "america/argentina/la_rioja": c["AR"],
    "america/argentina/mendoza": c["AR"],
    "america/argentina/rio_gallegos": c["AR"],
    "america/argentina/salta": c["AR"],
    "america/argentina/san_juan": c["AR"],
    "america/argentina/san_luis": c["AR"],
    "america/argentina/tucuman": c["AR"],
    "america/argentina/ushuaia": c["AR"],
    "asia/yerevan": c["AM"],
    "america/aruba": c["AW"],
    "antarctica/macquarie": c["AU"],
    "australia/adelaide": c["AU"],
    "australia/brisbane": c["AU"],
    "australia/broken_hill": c["AU"],
    "australia/currie": c["AU"],
    "australia/darwin": c["AU"],
    "australia/eucla": c["AU"],
    "australia/hobart": c["AU"],
    "australia/lindeman": c["AU"],
    "australia/lord_howe": c["AU"],
    "australia/melbourne": c["AU"],
    "australia/perth": c["AU"],
    "australia/sydney": c["AU"],
    "europe/vienna": c["AT"],
    "asia/baku": c["AZ"],
    "asia/bahrain": c["BH"],
    "asia/dhaka": c["BD"],
    "america/barbados": c["BB"],
    "europe/minsk": c["BY"],
    "europe/brussels": c["BE"],
    "america/belize": c["BZ"],
    "africa/porto-novo": c["BJ"],
    "atlantic/bermuda": c["BM"],
    "asia/thimphu": c["BT"],
    "america/la_paz": c["BO"],
    "europe/sarajevo": c["BA"],
    "africa/gaborone": c["BW"],
    "europe/oslo": c["NO"],
    "america/araguaina": c["BR"],
    "america/bahia": c["BR"],
    "america/belem": c["BR"],
    "america/boa_vista": c["BR"],
    "america/campo_grande": c["BR"],
    "america/cuiaba": c["BR"],
    "america/eirunepe": c["BR"],
    "america/fortaleza": c["BR"],
    "america/maceio": c["BR"],
    "america/manaus": c["BR"],
    "america/noronha": c["BR"],
    "america/porto_velho": c["BR"],
    "america/recife": c["BR"],
    "america/rio_branco": c["BR"],
    "america/santarem": c["BR"],
    "america/sao_paulo": c["BR"],
    "indian/chagos": c["IO"],
    "asia/brunei": c["BN"],
    "europe/sofia": c["BG"],
    "africa/ouagadougou": c["BF"],
    "africa/bujumbura": c["BI"],
    "asia/phnom_penh": c["KH"],
    "africa/douala": c["CM"],
    "america/atikokan": c["CA"],
    "america/blanc-sablon": c["CA"],
    "america/cambridge_bay": c["CA"],
    "america/creston": c["CA"],
    "america/dawson": c["CA"],
    "america/dawson_creek": c["CA"],
    "america/edmonton": c["CA"],
    "america/fort_nelson": c["CA"],
    "america/glace_bay": c["CA"],
    "america/goose_bay": c["CA"],
    "america/halifax": c["CA"],
    "america/inuvik": c["CA"],
    "america/iqaluit": c["CA"],
    "america/moncton": c["CA"],
    "america/nipigon": c["CA"],
    "america/pangnirtung": c["CA"],
    "america/rainy_river": c["CA"],
    "america/rankin_inlet": c["CA"],
    "america/regina": c["CA"],
    "america/resolute": c["CA"],
    "america/st_johns": c["CA"],
    "america/swift_current": c["CA"],
    "america/thunder_bay": c["CA"],
    "america/toronto": c["CA"],
    "america/vancouver": c["CA"],
    "america/whitehorse": c["CA"],
    "america/winnipeg": c["CA"],
    "america/yellowknife": c["CA"],
    "atlantic/cape_verde": c["CV"],
    "america/cayman": c["KY"],
    "africa/bangui": c["CF"],
    "africa/ndjamena": c["TD"],
    "america/punta_arenas": c["CL"],
    "america/santiago": c["CL"],
    "pacific/easter": c["CL"],
    "asia/shanghai": c["CN"],
    "asia/urumqi": c["CN"],
    "indian/christmas": c["CX"],
    "indian/cocos": c["CC"],
    "america/bogota": c["CO"],
    "indian/comoro": c["KM"],
    "africa/brazzaville": c["CG"],
    "pacific/rarotonga": c["CK"],
    "america/costa_rica": c["CR"],
    "africa/abidjan": c["CI"],
    "europe/zagreb": c["HR"],
    "america/havana": c["CU"],
    "america/curacao": c["CW"],
    "asia/famagusta": c["CY"],
    "asia/nicosia": c["CY"],
    "europe/prague": c["CZ"],
    "africa/kinshasa": c["CD"],
    "africa/lubumbashi": c["CD"],
    "europe/copenhagen": c["DK"],
    "africa/djibouti": c["DJ"],
    "america/dominica": c["DM"],
    "america/santo_domingo": c["DO"],
    "asia/dili": c["TL"],
    "america/guayaquil": c["EC"],
    "pacific/galapagos": c["EC"],
    "africa/cairo": c["EG"],
    "america/el_salvador": c["SV"],
    "africa/malabo": c["GQ"],
    "africa/asmara": c["ER"],
    "europe/tallinn": c["EE"],
    "africa/addis_ababa": c["ET"],
    "atlantic/stanley": c["FK"],
    "atlantic/faroe": c["FO"],
    "pacific/fiji": c["FJ"],
    "europe/helsinki": c["FI"],
    "europe/paris": c["FR"],
    "america/cayenne": c["GF"],
    "pacific/gambier": c["PF"],
    "pacific/marquesas": c["PF"],
    "pacific/tahiti": c["PF"],
    "indian/kerguelen": c["HM"],
    "africa/libreville": c["GA"],
    "africa/banjul": c["GM"],
    "asia/tbilisi": c["GE"],
    "europe/berlin": c["DE"],
    "europe/busingen": c["DE"],
    "africa/accra": c["GH"],
    "europe/gibraltar": c["GI"],
    "europe/athens": c["GR"],
    "america/danmarkshavn": c["GL"],
    "america/nuuk": c["GL"],
    "america/scoresbysund": c["GL"],
    "america/thule": c["GL"],
    "america/grenada": c["GD"],
    "america/guadeloupe": c["GP"],
    "pacific/guam": c["GU"],
    "america/guatemala": c["GT"],
    "europe/guernsey": c["GG"],
    "africa/conakry": c["GN"],
    "africa/bissau": c["GW"],
    "america/guyana": c["GY"],
    "america/port-au-prince": c["HT"],
    "america/tegucigalpa": c["HN"],
    "asia/hong_kong": c["HK"],
    "europe/budapest": c["HU"],
    "atlantic/reykjavik": c["IS"],
    "asia/kolkata": c["IN"],
    "asia/jakarta": c["ID"],
    "asia/jayapura": c["ID"],
    "asia/makassar": c["ID"],
    "asia/pontianak": c["ID"],
    "asia/tehran": c["IR"],
    "asia/baghdad": c["IQ"],
    "europe/dublin": c["IE"],
    "asia/jerusalem": c["IL"],
    "europe/rome": c["IT"],
    "america/jamaica": c["JM"],
    "asia/tokyo": c["JP"],
    "europe/jersey": c["JE"],
    "asia/amman": c["JO"],
    "asia/almaty": c["KZ"],
    "asia/aqtau": c["KZ"],
    "asia/aqtobe": c["KZ"],
    "asia/atyrau": c["KZ"],
    "asia/oral": c["KZ"],
    "asia/qostanay": c["KZ"],
    "asia/qyzylorda": c["KZ"],
    "africa/nairobi": c["KE"],
    "pacific/enderbury": c["KI"],
    "pacific/kiritimati": c["KI"],
    "pacific/tarawa": c["KI"],
    "europe/belgrade": c["RS"],
    "asia/kuwait": c["KW"],
    "asia/bishkek": c["KG"],
    "asia/vientiane": c["LA"],
    "europe/riga": c["LV"],
    "asia/beirut": c["LB"],
    "africa/maseru": c["LS"],
    "africa/monrovia": c["LR"],
    "africa/tripoli": c["LY"],
    "europe/vaduz": c["LI"],
    "europe/vilnius": c["LT"],
    "europe/luxembourg": c["LU"],
    "asia/macau": c["MO"],
    "europe/skopje": c["MK"],
    "indian/antananarivo": c["MG"],
    "africa/blantyre": c["MW"],
    "asia/kuala_lumpur": c["MY"],
    "asia/kuching": c["MY"],
    "indian/maldives": c["MV"],
    "africa/bamako": c["ML"],
    "europe/malta": c["MT"],
    "europe/isle_of_man": c["IM"],
    "pacific/kwajalein": c["MH"],
    "pacific/majuro": c["MH"],
    "america/martinique": c["MQ"],
    "africa/nouakchott": c["MR"],
    "indian/mauritius": c["MU"],
    "indian/mayotte": c["YT"],
    "america/bahia_banderas": c["MX"],
    "america/cancun": c["MX"],
    "america/chihuahua": c["MX"],
    "america/hermosillo": c["MX"],
    "america/matamoros": c["MX"],
    "america/mazatlan": c["MX"],
    "america/merida": c["MX"],
    "america/mexico_city": c["MX"],
    "america/monterrey": c["MX"],
    "america/ojinaga": c["MX"],
    "america/tijuana": c["MX"],
    "pacific/chuuk": c["FM"],
    "pacific/kosrae": c["FM"],
    "pacific/pohnpei": c["FM"],
    "europe/chisinau": c["MD"],
    "europe/monaco": c["MC"],
    "asia/choibalsan": c["MN"],
    "asia/hovd": c["MN"],
    "asia/ulaanbaatar": c["MN"],
    "europe/podgorica": c["ME"],
    "america/montserrat": c["MS"],
    "africa/casablanca": c["MA"],
    "africa/maputo": c["MZ"],
    "asia/yangon": c["MM"],
    "africa/windhoek": c["NA"],
    "pacific/nauru": c["NR"],
    "asia/kathmandu": c["NP"],
    "europe/amsterdam": c["NL"],
    "pacific/noumea": c["NC"],
    "pacific/auckland": c["NZ"],
    "pacific/chatham": c["NZ"],
    "america/managua": c["NI"],
    "africa/niamey": c["NE"],
    "africa/lagos": c["NG"],
    "pacific/niue": c["NU"],
    "pacific/norfolk": c["NF"],
    "asia/pyongyang": c["KP"],
    "pacific/saipan": c["MP"],
    "asia/muscat": c["OM"],
    "asia/karachi": c["PK"],
    "pacific/palau": c["PW"],
    "asia/gaza": c["PS"],
    "asia/hebron": c["PS"],
    "america/panama": c["PA"],
    "pacific/bougainville": c["PG"],
    "pacific/port_moresby": c["PG"],
    "america/asuncion": c["PY"],
    "america/lima": c["PE"],
    "asia/manila": c["PH"],
    "pacific/pitcairn": c["PN"],
    "europe/warsaw": c["PL"],
    "atlantic/azores": c["PT"],
    "atlantic/madeira": c["PT"],
    "europe/lisbon": c["PT"],
    "america/puerto_rico": c["PR"],
    "asia/qatar": c["QA"],
    "indian/reunion": c["RE"],
    "europe/bucharest": c["RO"],
    "asia/anadyr": c["RU"],
    "asia/barnaul": c["RU"],
    "asia/chita": c["RU"],
    "asia/irkutsk": c["RU"],
    "asia/kamchatka": c["RU"],
    "asia/khandyga": c["RU"],
    "asia/krasnoyarsk": c["RU"],
    "asia/magadan": c["RU"],
    "asia/novokuznetsk": c["RU"],
    "asia/novosibirsk": c["RU"],
    "asia/omsk": c["RU"],
    "asia/sakhalin": c["RU"],
    "asia/srednekolymsk": c["RU"],
    "asia/tomsk": c["RU"],
    "asia/ust-nera": c["RU"],
    "asia/vladivostok": c["RU"],
    "asia/yakutsk": c["RU"],
    "asia/yekaterinburg": c["RU"],
    "europe/astrakhan": c["RU"],
    "europe/kaliningrad": c["RU"],
    "europe/kirov": c["RU"],
    "europe/moscow": c["RU"],
    "europe/samara": c["RU"],
    "europe/saratov": c["RU"],
    "europe/ulyanovsk": c["RU"],
    "europe/volgograd": c["RU"],
    "africa/kigali": c["RW"],
    "atlantic/st_helena": c["SH"],
    "america/st_kitts": c["KN"],
    "america/st_lucia": c["LC"],
    "america/miquelon": c["PM"],
    "america/st_vincent": c["VC"],
    "america/st_barthelemy": c["BL"],
    "america/marigot": c["MF"],
    "pacific/apia": c["WS"],
    "europe/san_marino": c["SM"],
    "africa/sao_tome": c["ST"],
    "asia/riyadh": c["SA"],
    "africa/dakar": c["SN"],
    "indian/mahe": c["SC"],
    "africa/freetown": c["SL"],
    "asia/singapore": c["SG"],
    "europe/bratislava": c["SK"],
    "europe/ljubljana": c["SI"],
    "pacific/guadalcanal": c["SB"],
    "africa/mogadishu": c["SO"],
    "africa/johannesburg": c["ZA"],
    "atlantic/south_georgia": c["GS"],
    "asia/seoul": c["KR"],
    "africa/juba": c["SS"],
    "africa/ceuta": c["ES"],
    "atlantic/canary": c["ES"],
    "europe/madrid": c["ES"],
    "asia/colombo": c["LK"],
    "africa/khartoum": c["SD"],
    "america/paramaribo": c["SR"],
    "arctic/longyearbyen": c["SJ"],
    "africa/mbabane": c["SZ"],
    "europe/stockholm": c["SE"],
    "europe/zurich": c["CH"],
    "asia/damascus": c["SY"],
    "asia/taipei": c["TW"],
    "asia/dushanbe": c["TJ"],
    "africa/dar_es_salaam": c["TZ"],
    "asia/bangkok": c["TH"],
    "america/nassau": c["BS"],
    "africa/lome": c["TG"],
    "pacific/fakaofo": c["TK"],
    "pacific/tongatapu": c["TO"],
    "america/port_of_spain": c["TT"],
    "africa/tunis": c["TN"],
    "europe/istanbul": c["TR"],
    "asia/ashgabat": c["TM"],
    "america/grand_turk": c["TC"],
    "pacific/funafuti": c["TV"],
    "africa/kampala": c["UG"],
    "europe/kiev": c["UA"],
    "europe/simferopol": c["UA"],
    "europe/uzhgorod": c["UA"],
    "europe/zaporozhye": c["UA"],
    "asia/dubai": c["AE"],
    "europe/london": c["GB"],
    "america/adak": c["US"],
    "america/anchorage": c["US"],
    "america/boise": c["US"],
    "america/chicago": c["US"],
    "america/denver": c["US"],
    "america/detroit": c["US"],
    "america/indiana/indianapolis": c["US"],
    "america/indiana/knox": c["US"],
    "america/indiana/marengo": c["US"],
    "america/indiana/petersburg": c["US"],
    "america/indiana/tell_city": c["US"],
    "america/indiana/vevay": c["US"],
    "america/indiana/vincennes": c["US"],
    "america/indiana/winamac": c["US"],
    "america/juneau": c["US"],
    "america/kentucky/louisville": c["US"],
    "america/kentucky/monticello": c["US"],
    "america/los_angeles": c["US"],
    "america/menominee": c["US"],
    "america/metlakatla": c["US"],
    "america/new_york": c["US"],
    "america/nome": c["US"],
    "america/north_dakota/beulah": c["US"],
    "america/north_dakota/center": c["US"],
    "america/north_dakota/new_salem": c["US"],
    "america/phoenix": c["US"],
    "america/sitka": c["US"],
    "america/yakutat": c["US"],
    "pacific/honolulu": c["US"],
    "pacific/midway": c["UM"],
    "pacific/wake": c["UM"],
    "america/montevideo": c["UY"],
    "asia/samarkand": c["UZ"],
    "asia/tashkent": c["UZ"],
    "pacific/efate": c["VU"],
    "europe/vatican": c["VA"],
    "america/caracas": c["VE"],
    "asia/ho_chi_minh": c["VN"],
    "america/tortola": c["VG"],
    "america/st_thomas": c["VI"],
    "pacific/wallis": c["WF"],
    "africa/el_aaiun": c["EH"],
    "asia/aden": c["YE"],
    "africa/lusaka": c["ZM"],
    "africa/harare": c["ZW"]
  };
  return () => countriesCodeByTimeZones;
}
const getCountriesFinalList = createCountriesDataByTimeZones();
export default getCountriesFinalList;
export { getCountriesFinalList };